name: "OpenWebUI with Ollama"
description: "Get up and running with OpenWebUI and Ollama for large language models"
version: "0.0.1"
slug: "openwebui_ollama"
arch:
  - aarch64
  - amd64
url: https://github.com/open-webui/open-webui
map:
  - config:rw
image: ghcr.io/open-webui/open-webui:main
init: false
ingress: true
ingress_port: 13000
ingress_stream: true
ports:
  3000/tcp: 13000
ports_description:
  3000/tcp: "OpenWebUI Interface"
startup: application
watchdog: tcp://[HOST]:[PORT:13000]